version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/poll-app
    file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 30
      runas: root

  AfterInstall:
    - location: scripts/install.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 30
      runas: root